### ISSUE TITLE
Node setup error

### ISSUE THREAD

**Issue by clusterfari** [nemtech/symbol-bootstrap#206]
**Describe the bug**
During the bootstrap installation, on a LInux 18.04 operating system,
I run the command

symbol-bootstrap start -p mainnet -a peer

and receive the following error output after entering the password:

2021-03-19T22:54:23.445Z info Password has been provided
2021-03-19T22:54:23.498Z info Generating config from preset mainnet
2021-03-19T22:54:23.498Z info Assembly preset peer
2021-03-19T22:54:23.576Z info Generating Main account...
2021-03-19T22:54:23.615Z info Generating Transport account...
2021-03-19T22:54:23.644Z info Generating Remote account...
2021-03-19T22:54:23.654Z info Generating VRF account...
2021-03-19T22:54:23.659Z error Unknown error generating the configuration. Cannot read property 'mkdir' of undefined
2021-03-19T22:54:23.660Z error The target folder 'target' should be deleted!!!
TypeError: Cannot read property 'mkdir' of undefined
at Function.mkdir (/usr/local/lib/node_modules/symbol-bootstrap/lib/service/BootstrapUtils.js:300:29)
at ConfigService.run (/usr/local/lib/node_modules/symbol-bootstrap/lib/service/ConfigService.js:97:51)
at
at process._tickCallback (internal/process/next_tick.js:188:7)
TypeError: Cannot read property 'mkdir' of undefined

Do you have an idea what could cause this problem?
**To Reproduce**
To reproduce the behavior:
1. Write the full executed command or script
2. Include the content of any custom preset file.

**Expected behavior**

**Logs**
If applicable, add the full or partial logs to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. MacOs, Ubuntu]
 - Tool Version
 - Docker Version
 - Node Version

**Additional context**

**Comment by rg911** [comment]
are you using node 8? have you tried using node 10+?

**Comment by clusterfari** [comment]
Uninstalling Ubuntu 18.04 and setting everything up in Ubuntu 20.04 solved the problem

**Comment by fboucquez** [comment]
You can upgrade to node 12+ in ubuntu 18 without going to ubuntu 20. 

For example:

```
curl -sL https://deb.nodesource.com/setup_15.x | sudo -E bash -
sudo apt-get install -y nodejs
```
