### ISSUE TITLE
Invalid ca private key while setting up the Bootstrap

### ISSUE THREAD

**Issue by alex-core-0x** [nemtech/symbol-bootstrap#219]
Log:

```
                         _             _         _                    _         _
  ___  _   _  _ __ ___  | |__    ___  | |       | |__    ___    ___  | |_  ___ | |_  _ __  __ _  _ __
 / __|| | | || '_ ` _ \ | '_ \  / _ \ | | _____ | '_ \  / _ \  / _ \ | __|/ __|| __|| '__|/ _` || '_ \
 \__ \| |_| || | | | | || |_) || (_) || ||_____|| |_) || (_) || (_) || |_ \__ \| |_ | |  | (_| || |_) |
 |___/ \__, ||_| |_| |_||_.__/  \___/ |_|       |_.__/  \___/  \___/  \__||___/ \__||_|   \__,_|| .__/
       |___/                                                                                    |_|
2021-03-15T14:26:39.709Z info     Password has been provided
2021-03-15T14:26:39.735Z info     Generating config from preset testnet
2021-03-15T14:26:39.736Z info     Assembly preset dual
2021-03-15T14:26:39.736Z info     Custom preset file supernode.yml
2021-03-15T14:26:39.756Z info     Main Account TBCGM5M5BFP3MUOIK3L6IDICL26H6TGNT5ASEJA has been provided
2021-03-15T14:26:39.757Z info     Generating Transport account...
2021-03-15T14:26:39.804Z info     Remote Account TA7PX6PUKRCRGMTNZSJJ5YUQJQBX3KHFQGLUBSI has been provided
2021-03-15T14:26:39.809Z info     VRF Account TBSSZOC4JL6NZKDXDTA3CXQRCPMGUKK4SIWLDEI has been provided
? Enter the 64 HEX private key of the Node's 'api-node' Main account with Addres
s: TBCGM5M5BFP3MUOIK3L6IDICL26H6TGNT5ASEJA and Public Key: 776c6987cdbe53e93a5db
93a9be28f4f9060bc48be73515d1fee6391eae4440b: ***********************************
2021-03-15T14:26:39.887Z info     User for docker resolved: 0:0
2021-03-15T14:26:39.887Z error    YOU ARE RUNNING BOOTSTRAP AS ROOT!!!! THIS IS NOT RECOMMENDED!!!
2021-03-15T14:26:39.888Z info     Running image using Exec: symbolplatform/symbol-server:tools-gcc-0.10.1.8 bash createNodeCertificates.sh
time="2021-03-15T14:26:49.587726002Z" level=info msg="shim containerd-shim started" address="unix:///run/containerd/s/6d8efd157557ab7f9cfa2f2525d2edd8358aaa7ea6d8fe8327a60772c62c8212" debug=false pid=223
time="2021-03-15T14:26:50.116436919Z" level=info msg="shim reaped" id=1b319ba20784f68567b0c1507fbf5f0a0f538df7c806613db6eb4ca0ba78b193
time="2021-03-15T14:26:50.127045209Z" level=info msg="ignoring event" module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
2021-03-15T14:26:50.973Z info     Certificate for node api-node created
2021-03-15T14:26:50.974Z error    Unknown error generating the configuration. Invalid ca private key
2021-03-15T14:26:50.974Z error    The target folder 'target' should be deleted!!!
Error: Invalid ca private key
    at Function.validateIsTrue (/usr/lib/node_modules/symbol-bootstrap/lib/service/BootstrapUtils.js:180:19)
    at CertificateService.run (/usr/lib/node_modules/symbol-bootstrap/lib/service/CertificateService.js:103:41)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    Error: Invalid ca private key
```

```
echo "$KEY" | symbol-bootstrap config -r -p $PRESET -a dual --password=$PASSWORD -c $PRESET_FILE
```

```
privateKeySecurityMode: PROMPT_MAIN
nodes:
- rewardProgram: SuperNode
  host: 136.244.104.254
  mainPublicKey: 918441ea7f82dbd7cd912681dbe2206e4fd5f13d8044a2265a4b312ae25282f9
  remotePrivateKey: f8a9edf47c4941d321f50b705b4b771e064b83247055a506428ec7bf9a0afe04
  vrfPrivateKey: b508b3eee3a54bdbca648fc38e977c72f681659cd5fbf2372ff1033d2b55e129
```

```
main private key: 52f47ba18b3298b0eed8a2639d3c2ac3da8c6774a3e2129b5749eafe35c4b9a3
```

Specs: Ubuntu 20.04; Docker version 19.03.8, build afacb8b7f0

See the discussion here: https://nem2.slack.com/archives/C9YKR0EUX/p1615819403229000

**Comment by fboucquez** [comment]
I cannot currently replicate your issue. Error: Invalid ca private key is an error stating that certificate generation didn't produce the expected private keys. 

Try not using echo "$KEY" | and not running as root. Remove all the params to the bare minimum 

Please follow https://forum.nem.io/t/complete-guide-to-run-a-dual-node-on-centos-8-using-symbol-bootstrap/29268 guide

**Comment by alex-core-0x** [comment]
> 
> 
> I cannot currently replicate your issue. Error: Invalid ca private key is an error stating that certificate generation didn't produce the expected private keys.
> 
> Try not using echo "$KEY" | and not running as root. Remove all the params to the bare minimum
> 
> Please follow https://forum.nem.io/t/complete-guide-to-run-a-dual-node-on-centos-8-using-symbol-bootstrap/29268 guide

Already tried.

Also tried not use `echo`, and tried from non-root.

**Comment by segfaultxavi** [comment]
Not sure if it's relevant, but I had problems with permissions when node.js was installed from apt. If I install from [nvm ](https://github.com/nvm-sh/nvm) instead never again had to run with sudo.

**Comment by fboucquez** [comment]
Fixed in dev
