### ISSUE TITLE
First Docker start ➡ MondoDB does't start; Restart ➡ MondoDB starts, but Docker get broken

### ISSUE THREAD

**Issue by alex-core-0x** [nemtech/symbol-bootstrap#233]
```
CONTAINER ID        IMAGE                              COMMAND                  CREATED             STATUS              PORTS                    NAMES
057b3faa8290        symbolplatform/symbol-rest:2.3.5   "docker-entrypoint.s…"   2 days ago          Up 6 seconds        0.0.0.0:3000->3000/tcp   rest-gateway
b3c270659740        mongo:4.4.3-bionic                 "docker-entrypoint.s…"   2 days ago          Up 8 seconds        27017/tcp                db
```
Through bootstrap, doesn't work.
```
api-broker exited with code 253

api-node        | Copyright (c) Jaguar0625, gimre, BloodyRookie, Tech Bureau, Corp.
api-node        | catapult version: 0.10.1.8 (public)
api-node        | loading resources from "./server-config/resources"
api-node        | loading configuration from "./server-config/resources/config-inflation.properties"
api-node        | loading configuration from "./server-config/resources/config-extensions-recovery.properties"
api-node        | loading configuration from "./server-config/resources/config-user.properties"
api-node        | loading configuration from "./server-config/resources/config-logging-recovery.properties"
api-node        | loading configuration from "./server-config/resources/config-node.properties"
api-node        | loading configuration from "./server-config/resources/config-network.properties"
api-node        | 2021-04-06 08:59:35.120728 0x00007f9ab0a3e400: <warning> (io::FileLock.cpp@75) LockOpen failed: 17
api-node        | 2021-04-06 08:59:35.120755 0x00007f9ab0a3e400: <fatal> (process::ProcessMain.cpp@136) could not acquire instance lock "./data/recovery.lock"
api-node        | !!!! server recovery has CRASHED!
api-node exited with code 253

api-node exited with code 253
```
Is it because of broken recovery?
```
api-broker      | 2021-04-06 08:59:32.571040 0x00007ff57675d400: <fatal> (local::HostUtils.h@43) unhandled exception while boot!
api-broker      | /catapult-src/src/catapult/io/FileQueue.cpp(133): Throw in function bool catapult::io::FileQueueReader::process(catapult::consumer<const std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&>&)
api-broker      | Dynamic exception type: boost::wrapexcept<catapult::catapult_error<std::runtime_error> >
api-broker      | std::exception::what: reading from file queue failed due to missing message file
api-broker      | [catapult::ErrorParam1*] = "./data/spool/state_change/0000000000000000.dat"
api-broker      |
api-broker      | 2021-04-06 08:59:32.571343 0x00007ff57675d400: <error> (local::HostUtils.h@44) Throwing exception: reading from file queue failed due to missing message file
api-broker      | 2021-04-06 08:59:32.571447 0x00007ff57675d400: <fatal> (process::ProcessMain.cpp@75)
api-broker      | thread: recovery catapu
api-broker      | unhandled exception while running local node!
api-broker      | /catapult-src/src/catapult/local/HostUtils.h(44): Throw in function std::unique_ptr<_Tp> catapult::local::CreateAndBootHost(TArgs&& ...) [with THost = catapult::local::{anonymous}::DefaultRecoveryOrchestrator; TArgs = {std::unique_ptr<catapult::extensions::ProcessBootstrapper, std::default_delete<catapult::extensions::ProcessBootstrapper> >}]
api-broker      | Dynamic exception type: boost::wrapexcept<catapult::catapult_error<std::runtime_error> >
api-broker      | std::exception::what: reading from file queue failed due to missing message file
api-broker      |
api-broker      | /symbol-commands/start.sh: line 70:    11 Aborted                 (core dumped) $catapultAppFolder/bin/catapult.recovery "$config"
api-broker      | !!!! broker recovery has CRASHED!
api-broker      | RUNNING broker NORMAL api-broker
api-broker      | !!!! Have lock file present, going to run recovery in broker mode....
api-broker      | Copyright (c) Jaguar0625, gimre, BloodyRookie, Tech Bureau, Corp.
api-broker      | catapult version: 0.10.1.8 (public)
api-broker      | loading resources from "./broker-config/resources"
api-broker      | loading configuration from "./broker-config/resources/config-inflation.properties"
api-broker      | loading configuration from "./broker-config/resources/config-extensions-recovery.properties"
api-broker      | loading configuration from "./broker-config/resources/config-user.properties"
api-broker      | loading configuration from "./broker-config/resources/config-logging-recovery.properties"
api-broker      | loading configuration from "./broker-config/resources/config-node.properties"
api-broker      | loading configuration from "./broker-config/resources/config-network.properties"
api-broker      | 2021-04-06 08:59:33.968659 0x00007f0057959400: <warning> (io::FileLock.cpp@75) LockOpen failed: 17
api-broker      | 2021-04-06 08:59:33.968672 0x00007f0057959400: <fatal> (process::ProcessMain.cpp@136) could not acquire instance lock "./data/recovery.lock"
api-broker      | !!!! broker recovery has CRASHED!
api-node exited with code 253
```

After `target` deletion and starting again:
```
api-node        | 2021-04-06 10:22:28.400774 0x00007f368744f700: <info> (chain::RemoteApiForwarder.h@69) completed 'synchronizer task' (api-01-eu-west-1 @ api-01.eu-west-1.testnet.symboldev.network:7900) with result Success
api-node        | 2021-04-06 10:22:29.444902 0x00007f36697fa700: <info> (disruptor::ConsumerDispatcher.cpp@44) completing processing of element 5 (360 blocks (heights 1442 - 1801) [9A44C088] from Remote_Pull with size 492KB 432B), last consumer is 0 elements behind
rest-gateway    | warn: db connection failed, retrying in 24000ms failed to connect to server [db:27017] on first connect [Error: getaddrinfo ENOTFOUND db
rest-gateway    |     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26) {
rest-gateway    |   name: 'MongoNetworkError'
rest-gateway    | }] {"name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [db:27017] on first connect [Error: getaddrinfo ENOTFOUND db\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26) {\n  name: 'MongoNetworkError'\n}]\n    at Pool.<anonymous> (/app/catapult-rest/rest/node_modules/mongodb/lib/core/topologies/server.js:438:11)\n    at Pool.emit (events.js:315:20)\n    at /app/catapult-rest/rest/node_modules/mongodb/lib/core/connection/pool.js:562:14\n    at /app/catapult-rest/rest/node_modules/mongodb/lib/core/connection/pool.js:995:11\n    at /app/catapult-rest/rest/node_modules/mongodb/lib/core/connection/connect.js:32:7\n    at callback (/app/catapult-rest/rest/node_modules/mongodb/lib/core/connection/connect.js:280:5)\n    at Socket.<anonymous> (/app/catapult-rest/rest/node_modules/mongodb/lib/core/connection/connect.js:310:7)\n    at Object.onceWrapper (events.js:422:26)\n    at Socket.emit (events.js:315:20)\n    at emitErrorNT (internal/streams/destroy.js:92:8)","timestamp":"2021-04-06T10:22:30.572Z"}
api-broker      | 2021-04-06 10:22:35.695347 0x00007f335b0cf400: <error> (extensions::ProcessBootstrapper.cpp@103) Throwing exception: Throw location unknown (consider using BOOST_THROW_EXCEPTION)
api-broker      | Dynamic exception type: boost::wrapexcept<boost::exception_detail::current_exception_std_exception_wrapper<std::runtime_error> >
api-broker      | std::exception::what: No suitable servers found: `serverSelectionTimeoutMS` expired: [Failed to resolve db]: generic server error
api-broker      | mongocxx::v_noabi::bulk_write_exception
api-broker      | 2021-04-06 10:22:35.695499 0x00007f335b0cf400: <fatal> (process::ProcessMain.cpp@75)
api-broker      | thread: broker catapult
api-broker      | unhandled exception while running local node!
api-broker      | /catapult-src/src/catapult/extensions/ProcessBootstrapper.cpp(103): Throw in function void catapult::extensions::{anonymous}::LoadExtension(const catapult::plugins::PluginModule&, catapult::extensions::ProcessBootstrapper&)
api-broker      | Dynamic exception type: boost::wrapexcept<catapult::plugins::plugin_load_error>
api-broker      | std::exception::what: Throw location unknown (consider using BOOST_THROW_EXCEPTION)
api-broker      | Dynamic exception type: boost::wrapexcept<boost::exception_detail::current_exception_std_exception_wrapper<std::runtime_error> >
api-broker      | std::exception::what: No suitable servers found: `serverSelectionTimeoutMS` expired: [Failed to resolve db]: generic server error
api-broker      | mongocxx::v_noabi::bulk_write_exception
api-broker      |
```
```
CONTAINER ID        IMAGE                                       COMMAND                  CREATED             STATUS              PORTS                    NAMES
5b73aa6b7b29        symbolplatform/symbol-server:gcc-0.10.1.8   "/bin/bash /symbol-c…"   2 days ago          Up 51 seconds       0.0.0.0:7900->7900/tcp   api-node
057b3faa8290        symbolplatform/symbol-rest:2.3.5            "docker-entrypoint.s…"   2 days ago          Up 52 seconds       0.0.0.0:3000->3000/tcp   rest-gateway
54d4e7bff5ce        symbolplatform/symbol-server:gcc-0.10.1.8   "/bin/bash /symbol-c…"   2 days ago          Up 16 seconds          
```
Mongo db doesn't launch.

```
{"t":{"$date":"2021-04-06T10:22:05.812+00:00"},"s":"I",  "c":"NETWORK",  "id":22943,   "ctx":"listener","msg":"Connection accepted","attr":{"remote":"127.0.0.1:34108","connectionId":1,"connectionCount":1}}
{"t":{"$date":"2021-04-06T10:22:05.818+00:00"},"s":"I",  "c":"NETWORK",  "id":51800,   "ctx":"conn1","msg":"client metadata","attr":{"remote":"127.0.0.1:34108","client":"conn1","doc":{"application":{"name":"MongoDB Shell"},"driver":{"name":"MongoDB Internal Client","version":"4.4.3"},"os":{"type":"Linux","name":"Ubuntu","architecture":"x86_64","version":"18.04"}}}}

/usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/mongoDbPrepare.js
{"t":{"$date":"2021-04-06T10:22:05.844+00:00"},"s":"I",  "c":"NETWORK",  "id":22944,   "ctx":"conn1","msg":"Connection ended","attr":{"remote":"127.0.0.1:34108","connectionId":1,"connectionCount":0}}
{"t":{"$date":"2021-04-06T10:22:06.018+00:00"},"s":"I",  "c":"NETWORK",  "id":22943,   "ctx":"listener","msg":"Connection accepted","attr":{"remote":"127.0.0.1:34110","connectionId":2,"connectionCount":1}}
{"t":{"$date":"2021-04-06T10:22:06.018+00:00"},"s":"I",  "c":"NETWORK",  "id":51800,   "ctx":"conn2","msg":"client metadata","attr":{"remote":"127.0.0.1:34110","client":"conn2","doc":{"application":{"name":"MongoDB Shell"},"driver":{"name":"MongoDB Internal Client","version":"4.4.3"},"os":{"type":"Linux","name":"Ubuntu","architecture":"x86_64","version":"18.04"}}}}
failed to load: /docker-entrypoint-initdb.d/mongoDbPrepare.js
exiting with code -3
{"t":{"$date":"2021-04-06T10:22:06.049+00:00"},"s":"I",  "c":"NETWORK",  "id":22944,   "ctx":"conn2","msg":"Connection ended","attr":{"remote":"127.0.0.1:34110","connectionId":2,"connectionCount":0}}
```
If we restart docker after that - Mongo db starts. But docker got broken.

This issue is follow up from https://github.com/nemtech/symbol-bootstrap/issues/219

<hr>

We are running the Symbol supernode inside the docker container. Basically, node containers are being run inside the main container.

The script used on clean VPS (without additional configurations, from root).
[symbol_test_new.txt](https://github.com/nemtech/symbol-bootstrap/files/6296670/symbol_test_new.txt)

**Comment by alex-core-0x** [comment]
After the latest update, MongoDB doesn't start again.

Logs:
[mongo.txt](https://github.com/nemtech/symbol-bootstrap/files/6294391/mongo.txt)

**Comment by alex-core-0x** [comment]
Issue updated main post updated.

**Comment by alex-core-0x** [comment]
Please create the same setup for the Symbol supernode, that we have for the NEM supernode 🙏

**Comment by fboucquez** [comment]
If you like better support, you need to specify how you create the docker image that runs bootstrap and the generated compose inside. This is an uncommon setup for Symbol.

**Comment by fboucquez** [comment]
Released
