### ISSUE TITLE
Unknown error generating the configuration. Cannot read property 'mkdir' of undefined

### ISSUE THREAD

**Issue by subhasisbanik** [nemtech/symbol-bootstrap#249]
I am trying to set up a mainnet symbol node in my VM.
I have installed the symbol-bootstrap with the commands below:

sudo apt update
sudo apt install nodejs npm docker docker-compose
node --version

Since I was facing EACCESS error, I followed the steps from https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally

And followed the below steps to proceed further:

npm install -g symbol-bootstrap
mkdir my-networks
cd my-networks

Now while running:
symbol-bootstrap start -p mainnet -a dual

I am facing the below error after providing the password:

Symbol_admin@Symbol-Maninet-Node:~/my-networks$ symbol-bootstrap start -p mainnet -a dual
                         _             _         _                    _         _
  ___  _   _  _ __ ___  | |__    ___  | |       | |__    ___    ___  | |_  ___ | |_  _ __  __ _  _ __
 / __|| | | || '_ ` _ \ | '_ \  / _ \ | | _____ | '_ \  / _ \  / _ \ | __|/ __|| __|| '__|/ _` || '_ \
 \__ \| |_| || | | | | || |_) || (_) || ||_____|| |_) || (_) || (_) || |_ \__ \| |_ | |  | (_| || |_) |
 |___/ \__, ||_| |_| |_||_.__/  \___/ |_|       |_.__/  \___/  \___/  \__||___/ \__||_|   \__,_|| .__/
       |___/                                                                                    |_|
? Enter password to use to encrypt and decrypt custom presets, addresses.yml, and preset.yml files. When providing a password, private keys will be encrypted. Keep this password in a secure place! ********
***
2021-05-13T14:42:17.395Z info     Password has been provided
2021-05-13T14:42:17.442Z info     Generating config from preset 'mainnet'
2021-05-13T14:42:17.443Z info     Using assembly 'dual'
2021-05-13T14:42:17.487Z info     Generating Main account...
2021-05-13T14:42:17.503Z info     Generating Transport account...
2021-05-13T14:42:17.509Z info     Generating Remote account...
2021-05-13T14:42:17.516Z info     Generating VRF account...
2021-05-13T14:42:17.522Z error    Unknown error generating the configuration. Cannot read property 'mkdir' of undefined
2021-05-13T14:42:17.522Z error    The target folder 'target' should be deleted!!!
TypeError: Cannot read property 'mkdir' of undefined
    at Function.mkdir (/home/Symbol_admin/.npm-global/lib/node_modules/symbol-bootstrap/lib/service/BootstrapUtils.js:313:29)
    at ConfigService.run (/home/Symbol_admin/.npm-global/lib/node_modules/symbol-bootstrap/lib/service/ConfigService.js:98:51)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    TypeError: Cannot read property 'mkdir' of undefined

FYI:
I am running :
Symbol_admin@Symbol-Maninet-Node:~/my-networks$ symbol-bootstrap --version
symbol-bootstrap/1.0.5 linux-x64 node-v8.10.0

**Comment by fboucquez** [comment]
Hi @subhasisbanik , your node version 8 is too old, try installing a node 12+
