### ISSUE TITLE
Error messages shortly after starting version 0.2.1 on newly installed Ubuntu20.04

### ISSUE THREAD

**Issue by garm01** [nemtech/symbol-bootstrap#64]
**error messages:**

- db exited with code 100

rest-gateway    | error: rest server is exiting due to error failed to connect to server [db:27017] on first connect [Error: getaddrinfo ENOTFOUND db
rest-gateway    |     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26) {
rest-gateway    |   name: 'MongoNetworkError'
rest-gateway    | }] {"name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [db:27017] on first connect [Error: getaddrinfo ENOTFOUND db\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26) {\n  name: 'MongoNetworkError'\n}]\n    at Pool.<anonymous> (/app/catapult-rest/rest/node_modules/mongodb/lib/core/topologies/server.js:438:11)\n    at Pool.emit (events.js:315:20)\n    at /app/catapult-rest/rest/node_modules/mongodb/lib/core/connection/pool.js:562:14\n    at /app/catapult-rest/rest/node_modules/mongodb/lib/core/connection/pool.js:995:11\n    at /app/catapult-rest/rest/node_modules/mongodb/lib/core/connection/connect.js:32:7\n    at callback (/app/catapult-rest/rest/node_modules/mongodb/lib/core/connection/connect.js:280:5)\n    at Socket.<anonymous> (/app/catapult-rest/rest/node_modules/mongodb/lib/core/connection/connect.js:310:7)\n    at Object.onceWrapper (events.js:422:26)\n    at Socket.emit (events.js:315:20)\n    at emitErrorNT (internal/streams/destroy.js:92:8)","timestamp":"2020-11-03T13:36:28.799Z"}
api-node        | 2020-11-03 13:36:29.346079 0x00007fad0effd700: <info> (ionet::PacketSocket.cpp@41) eof reading from socket: End of file

- rest-gateway exited with code 0

- api-broker exited with code 253

- api-broker exited with code 253

**my steps after Install the OS:**(default configuration v.0.2.1 without a custom preset.yml)

apt install apt-transport-https ca-certificates curl software-properties-common gnupg-agent 
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
apt-key fingerprint 0EBFCD88
add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
apt update
apt-cache policy docker-ce
apt install docker-ce
systemctl status docker
curl -L "https://github.com/docker/compose/releases/download/1.27.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose
apt update
apt upgrade
curl -sL https://deb.nodesource.com/setup_15.x -o nodesource_setup.sh
bash nodesource_setup.sh
apt install nodejs
open the ports 3000/7900/7901/7902
npm install -g symbol-bootstrap
npm install -g npm@7.0.7
symbol-bootstrap config -p testnet -a dual
symbol-bootstrap compose
symbol-bootstrap run

**Desktop:** 
 - Linux Ubuntu-2004-focal-64-minimal 5.4.0-47-generic
 - symbol-bootstrap v0.2.1
 - docker version 19.03.13, build 4484c46d9d
 - docker-compose version 1.27.4, build 40524192
 - Node v15.0.1

**Comment by garm01** [comment]
**the first lines after start, maybe it helps:**
2020-11-03T13:35:41.969Z info     f164ba21e17c: Pull complete
2020-11-03T13:35:42.060Z info     d179b2b5a419: Pull complete
2020-11-03T13:35:42.261Z info     96df770eddfa: Pull complete
2020-11-03T13:35:42.392Z info     Digest: sha256:6ad8417c1567cc07f834b389d953e0b5c4c7fb75a841671488b4ae93408e21ab
2020-11-03T13:35:42.578Z info     Status: Downloaded newer image for symbolplatform/symbol-server:gcc-0.10.0.3
2020-11-03T13:35:42.579Z info     docker.io/symbolplatform/symbol-server:gcc-0.10.0.3
2020-11-03T13:35:42.584Z info     Image pulled: docker.io/symbolplatform/symbol-server:gcc-0.10.0.3
2020-11-03T13:35:42.595Z info     6494c387442c: Pull complete
2020-11-03T13:35:42.806Z info     Digest: sha256:a89b09e8bc3153c5c87c52e36a7b6f992ee874c5329cc631e5d9542bf1cbfe31
2020-11-03T13:35:42.831Z info     317f77d899d5: Pull complete
2020-11-03T13:35:42.966Z info     Status: Downloaded newer image for mongo:4.2.6-bionic
2020-11-03T13:35:42.967Z info     docker.io/library/mongo:4.2.6-bionic
2020-11-03T13:35:42.972Z info     Image pulled: docker.io/library/mongo:4.2.6-bionic
2020-11-03T13:35:43.062Z info     Digest: sha256:5aa54ce2a911befc7441e233a01414bbeca57777b1b6634f3b4a83fb63c84cda
2020-11-03T13:35:43.146Z info     Status: Downloaded newer image for symbolplatform/symbol-rest:2.1.0
2020-11-03T13:35:43.147Z info     docker.io/symbolplatform/symbol-rest:2.1.0
2020-11-03T13:35:43.151Z info     Image pulled: docker.io/symbolplatform/symbol-rest:2.1.0
2020-11-03T13:35:43.158Z info     Spawn command: docker-compose -f target/docker/docker-compose.yml up --remove-orphans
Creating network "docker_default" with the default driver
Creating db ...
Creating db         ... done

Creating api-node   ...
Creating api-node     ... done
Creating rest-gateway ...
Creating rest-gateway ... done

Attaching to api-broker, db, api-node, rest-gateway
api-broker      | RUNNING runServerRecover.sh api-broker
db              **| about to fork child process, waiting until server is ready for connections.**
api-broker      | !!!! DO NOT HAVE ANY LOCK FILE... There is no need to recover
api-node        | RUNNING runServerRecover.sh api-node
api-broker      | RUNNING running startBroker.sh api-broker
db              | **forked process: 25**
api-broker      | Copyright (c) Jaguar0625, gimre, BloodyRookie, Tech Bureau, Corp.
api-broker      | catapult version: 0.10.0.3 (public)
api-broker      | loading resources from "./userconfig/resources"
api-broker      | loading configuration from "./userconfig/resources/config-inflation.properties"
api-broker      | loading configuration from "./userconfig/resources/config-extensions-broker.properties"
api-node        | !!!! DO NOT HAVE ANY LOCK FILE... There is no need to recover
db              | 2020-11-03T13:36:17.004+0000 I  CONTROL  [main] ***** SERVER RESTARTED *****
api-broker      | loading configuration from "./userconfig/resources/config-user.properties"
db              | 2020-11-03T13:36:17.007+0000 I  CONTROL  [main] Automatically disabling TLS 1.0, to force-enable TLS 1.0 specify --sslDisabledProtocols 'none'
api-node        | RUNNING startServer.sh api-node
db              | 2020-11-03T13:36:17.009+0000 W  ASIO     [main] No TransportLayer configured during NetworkInterface startup
api-broker      | loading configuration from "./userconfig/resources/config-logging-broker.properties"
db              | 2020-11-03T13:36:17.009+0000 I  CONTROL  [initandlisten] MongoDB starting : pid=25 port=27017 dbpath=/dbdata 64-bit host=9de7aa20177b
db              | 2020-11-03T13:36:17.009+0000 I  CONTROL  [initandlisten] db version v4.2.6
db              | 2020-11-03T13:36:17.009+0000 I  CONTROL  [initandlisten] git version: 20364840b8f1af16917e4c23c1b5f5efd8b352f8
db              | 2020-11-03T13:36:17.009+0000 I  CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.1.1  11 Sep 2018
db              | 2020-11-03T13:36:17.009+0000 I  CONTROL  [initandlisten] allocator: tcmalloc
db              | 2020-11-03T13:36:17.009+0000 I  CONTROL  [initandlisten] modules: none
db              | 2020-11-03T13:36:17.009+0000 I  CONTROL  [initandlisten] build environment:
api-broker      | loading configuration from "./userconfig/resources/config-node.properties"
api-broker      | loading configuration from "./userconfig/resources/config-network.properties"
api-node        | !!!! Going to start server now....
api-broker      | 2020-11-03 13:36:16.934469 0x00007fdc77d97200: <warning> (process::Platform.cpp@38)

**Comment by garm01** [comment]
**first lines after start:**
4ffe534daa34: Download complete
2020-11-03T13:35:32.765Z info     a4d269900d94: Pull complete
2020-11-03T13:35:34.390Z info     5e2526abb80a: Pull complete
2020-11-03T13:35:34.994Z info     d3eece1f39ec: Pull complete
2020-11-03T13:35:35.273Z info     358ed78d3204: Pull complete
2020-11-03T13:35:35.642Z info     1a878b8604ae: Pull complete
2020-11-03T13:35:36.037Z info     dde03a2883d0: Pull complete
2020-11-03T13:35:41.081Z info     4ffe534daa34: Pull complete
2020-11-03T13:35:41.969Z info     f164ba21e17c: Pull complete
2020-11-03T13:35:42.060Z info     d179b2b5a419: Pull complete
2020-11-03T13:35:42.261Z info     96df770eddfa: Pull complete
2020-11-03T13:35:42.392Z info     Digest: sha256:6ad8417c1567cc07f834b389d953e0b5c4c7fb75a841671488b4ae93408e21ab
2020-11-03T13:35:42.578Z info     Status: Downloaded newer image for symbolplatform/symbol-server:gcc-0.10.0.3
2020-11-03T13:35:42.579Z info     docker.io/symbolplatform/symbol-server:gcc-0.10.0.3
2020-11-03T13:35:42.584Z info     Image pulled: docker.io/symbolplatform/symbol-server:gcc-0.10.0.3
2020-11-03T13:35:42.595Z info     6494c387442c: Pull complete
2020-11-03T13:35:42.806Z info     Digest: sha256:a89b09e8bc3153c5c87c52e36a7b6f992ee874c5329cc631e5d9542bf1cbfe31
2020-11-03T13:35:42.831Z info     317f77d899d5: Pull complete
2020-11-03T13:35:42.966Z info     Status: Downloaded newer image for mongo:4.2.6-bionic
2020-11-03T13:35:42.967Z info     docker.io/library/mongo:4.2.6-bionic
2020-11-03T13:35:42.972Z info     Image pulled: docker.io/library/mongo:4.2.6-bionic
2020-11-03T13:35:43.062Z info     Digest: sha256:5aa54ce2a911befc7441e233a01414bbeca57777b1b6634f3b4a83fb63c84cda
2020-11-03T13:35:43.146Z info     Status: Downloaded newer image for symbolplatform/symbol-rest:2.1.0
2020-11-03T13:35:43.147Z info     docker.io/symbolplatform/symbol-rest:2.1.0
2020-11-03T13:35:43.151Z info     Image pulled: docker.io/symbolplatform/symbol-rest:2.1.0
2020-11-03T13:35:43.158Z info     Spawn command: docker-compose -f target/docker/docker-compose.yml up --remove-orphans
Creating network "docker_default" with the default driver
Creating db ...
Creating db         ... done

Creating api-node   ...
Creating api-node     ... done
Creating rest-gateway ...
Creating rest-gateway ... done

Attaching to api-broker, db, api-node, rest-gateway
api-broker      | RUNNING runServerRecover.sh api-broker
db              | **about to fork child process, waiting until server is ready for connections.**
api-broker      | !!!! DO NOT HAVE ANY LOCK FILE... There is no need to recover
api-node        | RUNNING runServerRecover.sh api-node
api-broker      | RUNNING running startBroker.sh api-broker
db              | **forked process: 25**
api-broker      | Copyright (c) Jaguar0625, gimre, BloodyRookie, Tech Bureau, Corp.
api-broker      | catapult version: 0.10.0.3 (public)
api-broker      | loading resources from "./userconfig/resources"
api-broker      | loading configuration from "./userconfig/resources/config-inflation.properties"
api-broker      | loading configuration from "./userconfig/resources/config-extensions-broker.properties"
api-node        | !!!! DO NOT HAVE ANY LOCK FILE... There is no need to recover
db              | 2020-11-03T13:36:17.004+0000 I  CONTROL  [main] ***** SERVER RESTARTED *****
api-broker      | loading configuration from "./userconfig/resources/config-user.properties"
db              | 2020-11-03T13:36:17.007+0000 I  CONTROL  [main] Automatically disabling TLS 1.0, to force-enable TLS 1.0 specify --sslDisabledProtocols 'none'
api-node        | RUNNING startServer.sh api-node
db              | 2020-11-03T13:36:17.009+0000 W  ASIO     [main] No TransportLayer configured during NetworkInterface startup
api-broker      | loading configuration from "./userconfig/resources/config-logging-broker.properties"
db              | 2020-11-03T13:36:17.009+0000 I  CONTROL  [initandlisten] MongoDB starting : pid=25 port=27017 dbpath=/dbdata 64-bit host=9de7aa20177b
db              | 2020-11-03T13:36:17.009+0000 I  CONTROL  [initandlisten] db version v4.2.6
db              | 2020-11-03T13:36:17.009+0000 I  CONTROL  [initandlisten] git version: 20364840b8f1af16917e4c23c1b5f5efd8b352f8
db              | 2020-11-03T13:36:17.009+0000 I  CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.1.1  11 Sep 2018
db              | 2020-11-03T13:36:17.009+0000 I  CONTROL  [initandlisten] allocator: tcmalloc
db              | 2020-11-03T13:36:17.009+0000 I  CONTROL  [initandlisten] modules: none
db              | 2020-11-03T13:36:17.009+0000 I  CONTROL  [initandlisten] build environment:
api-broker      | loading configuration from "./userconfig/resources/config-node.properties"
api-broker      | loading configuration from "./userconfig/resources/config-network.properties"
api-node        | !!!! Going to start server now....

**Comment by meyns** [comment]
I got the same error, problem was the db folder was not writeable.
I fixed the problem with the following procedure: Start like you normally would, and the exit. After that chmod the db folder so it is writeable and then restart the bootstrap. Had to delete the lock files underway because otherwise it would not load

This is the code I use:
symbol-bootstrap start -r -p testnet -a dual -d
symbol-bootstrap stop
sudo chmod -R go+w target/databases/db
rm target/nodes/api-node/data/broker.lock
rm target/nodes/api-node/data/server.lock
symbol-bootstrap run -d

**Comment by meyns** [comment]
This is still not fixed in 0.3.0, can't start bootstrap without my fix

**Comment by cryptoBeliever** [comment]
Got same issue on digitalocean droplet. Mongo failed to start with errors:

```
2020-12-15T19:10:29.808+0000 I  CONTROL  [main] ***** SERVER RESTARTED *****
2020-12-15T19:10:29.814+0000 I  CONTROL  [main] Automatically disabling TLS 1.0, to force-enable TLS 1.0 specify --sslDisabledProtocols 'none'
2020-12-15T19:10:29.816+0000 W  ASIO     [main] No TransportLayer configured during NetworkInterface startup
2020-12-15T19:10:29.816+0000 I  CONTROL  [initandlisten] MongoDB starting : pid=24 port=27017 dbpath=/dbdata 64-bit host=dc3dbb29b937
2020-12-15T19:10:29.816+0000 I  CONTROL  [initandlisten] db version v4.2.6
2020-12-15T19:10:29.816+0000 I  CONTROL  [initandlisten] git version: 20364840b8f1af16917e4c23c1b5f5efd8b352f8
2020-12-15T19:10:29.816+0000 I  CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.1.1  11 Sep 2018
2020-12-15T19:10:29.816+0000 I  CONTROL  [initandlisten] allocator: tcmalloc
2020-12-15T19:10:29.816+0000 I  CONTROL  [initandlisten] modules: none
2020-12-15T19:10:29.816+0000 I  CONTROL  [initandlisten] build environment:
2020-12-15T19:10:29.816+0000 I  CONTROL  [initandlisten]     distmod: ubuntu1804
2020-12-15T19:10:29.816+0000 I  CONTROL  [initandlisten]     distarch: x86_64
2020-12-15T19:10:29.816+0000 I  CONTROL  [initandlisten]     target_arch: x86_64
2020-12-15T19:10:29.816+0000 I  CONTROL  [initandlisten] options: { net: { bindIp: "127.0.0.1", port: 27017, tls: { mode: "disabled" } }, processManagement: { fork: true, pidFilePath: "/tmp/docker-entrypoint-temp-mongod.pid" }, storage: { dbPath: "/dbdata" }, systemLog: { destination: "file", logAppend: true, path: "/proc/1/fd/1" } }
2020-12-15T19:10:29.817+0000 I  STORAGE  [initandlisten] exception in initAndListen: IllegalOperation: Attempted to create a lock file on a read-only directory: /dbdata, terminating
2020-12-15T19:10:29.817+0000 I  NETWORK  [initandlisten] shutdown: going to close listening sockets...
2020-12-15T19:10:29.817+0000 I  -        [initandlisten] Stopping further Flow Control ticket acquisitions.
2020-12-15T19:10:29.817+0000 I  CONTROL  [initandlisten] now exiting
2020-12-15T19:10:29.817+0000 I  CONTROL  [initandlisten] shutting down with code:100
ERROR: child process failed, exited with error number 100
To see additional information in this output, start without the "--fork" option.
```
After changing permissions (https://github.com/nemtech/symbol-bootstrap/issues/64#issuecomment-724710569) it starts.

**Comment by cryptonit** [comment]
got same issue

this two commands fixed it

symbol-bootstrap stop
sudo chmod -R go+w target/databases/db

**Comment by fboucquez** [comment]
This issue has been fixed
